# Generated by Django 3.2 on 2021-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0002_laptop_lstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='lprice',
            field=models.IntegerField(default='0'),
        ),
    ]
